language: go
sudo: required     
go:  
- 1.11.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends p7zip-full build-essential ca-certificates curl gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-multilib git mingw-w64 mercurial pkg-config upx
  - mkdir -p $GOPATH/src/github.com/Psiphon-Labs/
  - cd $GOPATH/src/github.com/Psiphon-Labs/
  - git clone https://github.com/Psiphon-Labs/psiphon-tunnel-core
  - curl -o $HOME/rclone-v1.47.0-linux-amd64.zip -L https://github.com/ncw/rclone/releases/download/v1.47.0/rclone-v1.47.0-linux-amd64.zip
  - 7z x -o"$HOME/" $HOME/rclone-v1.47.0-linux-amd64.zip
script: 
- cd $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient/
- chmod +x ./make.bash
- ./make.bash linux
- ./make.bash windows
- ls bin/linux
- ls bin/windows
- chmod +x ~/rclone-v1.47.0-linux-amd64/rclone
- ~/rclone-v1.47.0-linux-amd64/rclone copy $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient/bin/linux/* :b2:$R_B2_UPLOAD_URI/
- ~/rclone-v1.47.0-linux-amd64/rclone copy $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient/bin/windows/* :b2:$R_B2_UPLOAD_URI/
