language: go
sudo: required     
go:  
- 1.11.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends build-essential ca-certificates curl gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-multilib git mingw-w64 mercurial pkg-config upx
  - go get github.com/Psiphon-Labs/psiphon-tunnel-core
script: 
- cd $GOPATH/src/github.com/Psiphon-Labs/psiphon-tunnel-core/ConsoleClient/
- ./make.sh linux
- ./make.sh windows
- ls bin/linux
- ls bin/windows
